/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.lib

import java.time.LocalDateTime

class Library(val books: List<String>, val opensAt: LocalDateTime, val closesAt: LocalDateTime) {

    fun someLibraryMethod(): Boolean {
        return true
    }
}
